services:
  hackaton.api:
    image: ${DOCKER_REGISTRY-}hackatonapi
    build:
      context: .
      dockerfile: Hackaton.API/Dockerfile
    ports:
        - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DatabaseConfiguration__DatabaseName=Hackaton
      - DatabaseConfiguration__SecretKey=aGFja2F0b25zZWNyZXRrZXkxNjIzNDI=
      - DatabaseConfiguration__TokenExpiration=86400
      - DatabaseConfiguration__Issuer=Hackaton
      - DatabaseConfiguration__Audience=HackatonAudience
    depends_on:
      - mongo
    networks:
      - hackaton-network
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - hackaton-network
networks:
      hackaton-network:
        driver: bridge
volumes:
    mongo-data:
