# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Hackaton

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./Hackaton.sln
    - name: Build
      run: dotnet build Hackaton/Hackaton.csproj --configuration Release --no-restore
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Contato API Docker Image
      uses: docker/build-push-action@v6.10.0
      with:
        file: ./Hackaton.API/Dockerfile
        push: true
        tags: pdaguis/hackaton:latest
